# Generated automatically from Makefile.in by configure.
SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = $(exec_prefix)/bin
infodir = $(prefix)/info
libdir = $(prefix)/lib

CC = gcc
CXX = g++
CPPFLAGS = 
CFLAGS = $(CPPFLAGS) -I/usr/local/lib -g -O2
LDFLAGS = -L/usr/local/lib 
LIBS = -lequ -lstr -lalgebrav -lhys -lm 
INSTALL = /usr/bin/ginstall -c

OPTS=

all: eqdata.cc
	$(CXX) $(OPTS) $(CFLAGS) $(LDFLAGS) eqdata.cc -o eqdata \
	-learthq -lstr -lequ -lmat -lhys -lalgebrav -lm

install:

uninstall:

clean:
	rm -f *.o *~ test response.dat

distclean:
	rm -f Makefile config.h config.status config.cache config.log

